@DientesLimpios.API_HostAddress = http://localhost:5273/api/citas



POST {{DientesLimpios.API_HostAddress}}
Content-Type: application/json

{
  "pacienteId": "019F630D-4566-7C9C-BD6D-DBF891440C42",
  "dentistaId": "019F810E-3CB7-744F-B0AE-43558414CE83",
  "consultorioId": "019F8166-EA59-7EBA-ACEC-2A0CB9BA95AF",
  "fechaInicio": "2026-09-01T13:00:00",
  "fechaFin": "2026-09-01T13:30:00"
}

###
GET {{DientesLimpios.API_HostAddress}}
Content-Type: application/json

###
GET {{DientesLimpios.API_HostAddress}}/019F816D-9998-7728-9EDE-50E1AE7385BC
Content-Type: application/json

###
GET {{DientesLimpios.API_HostAddress}}?pagina=2&registrosPorPagina=1
Content-Type: application/json

###
PUT {{DientesLimpios.API_HostAddress}}/019f630c-f3b9-74ca-afca-bae217870993
Content-Type: application/json

{
  "nombre": "Paciente A",
  "email": "alejandro@ejemplo.com"
}

###

POST {{DientesLimpios.API_HostAddress}}/019F816D-9998-7728-9EDE-50E1AE7385BC/completar
Content-Type: application/json

####

POST {{DientesLimpios.API_HostAddress}}/019F816C-4C10-7E57-9132-8B466BE155EA/cancelar
Content-Type: application/json
