@DientesLimpios.API_HostAddress = http://localhost:5273/api/consultorios

GET {{DientesLimpios.API_HostAddress}}/019F1085-DADC-78AA-9830-D95CE3E055F3
Content-Type: application/json

###

GET {{DientesLimpios.API_HostAddress}}/019F1085-DADC-78AA-9830-D95CE3E055F5
Content-Type: application/json

###

GET {{DientesLimpios.API_HostAddress}}/
Content-Type: application/json

###

POST {{DientesLimpios.API_HostAddress}}
Content-Type: application/json

{
  "nombre": "Consultorio A"
}

###

PUT {{DientesLimpios.API_HostAddress}}/019f21d5-1bc2-71ac-a4b0-1e67d23cb76b
Content-Type: application/json

{
  "nombre": "Consultorio Y"
}

###

DELETE {{DientesLimpios.API_HostAddress}}/019f2b0b-fb13-7666-81a1-4dd533a64462
Content-Type: application/json

###

