@DientesLimpios.API_HostAddress = http://localhost:5273/api/dentistas



POST {{DientesLimpios.API_HostAddress}}
Content-Type: application/json

{
  "nombre": "Dentista B",
  "email": "dentistaB@ejemplo.com"
}

###
GET {{DientesLimpios.API_HostAddress}}
Content-Type: application/json

###
GET {{DientesLimpios.API_HostAddress}}/019F8105-D439-756F-AA7D-9300AD1892B6
Content-Type: application/json

###
PUT {{DientesLimpios.API_HostAddress}}/019f810e-3cb7-744f-b0ae-43558414ce83
Content-Type: application/json

{
  "nombre": "Dentista A",
  "email": "actualizado@ejemplo.com"
}

